# To refresh existing project run `dipdup init --base --force` after modifying this file.
# To generate a new project from this replay run `dipdup new --replay <path_to_file>`.
#
spec_version: 3.0
replay:
  dipdup_version: 8
  template: demo_blank
  package: teia_ecosystem_indexer
  version: 0.0.1
  description: Teia and h=n token and transaction indexer built on dipdup
  license: MIT
  name: Kyle Grover
  email: kyle@kylegrover.com
  postgres_image: postgres:16
  postgres_data_path: /var/lib/postgresql/data
  hasura_image: hasura/graphql-engine:latest
  line_length: 120
  package_manager: uv
